name: Release Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Используем актуальную версию Node

      - name: Install Dependencies
        run: |
          npm install
          cd src-tauri
          cargo fetch

      - name: Build App
        run: |
          # Собираем фронтенд через npx, чтобы точно найти vite
          npx vite build
          # Собираем само приложение, зная что dist уже готов
          npx @tauri-apps/cli build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SirinNabat-Installer
          path: src-tauri/target/release/bundle/msi/*.msi