name: Release Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Force Install Dependencies
        run: |
          npm install
          # Принудительно скачиваем Vite и Tauri прямо на сервере Гитхаба!
          npm install vite @vitejs/plugin-react @tauri-apps/cli --no-save
          cd src-tauri
          cargo fetch

      - name: Build App
        run: |
          npx vite build
          npx tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SirinNabat-Installer
          path: src-tauri/target/release/bundle/msi/*.msi